name: Update Portal

on:
  workflow_dispatch:  
  push:
    branches: 
      - master 
 

jobs:
  update-portal:
    runs-on: ubuntu-latest
  
    steps:
    
    - name : checkout-repo
      uses: actions/checkout@v1
      id: checkout-repo 
      
    - name: zip files
      run: zip -r portal-input.zip *
      working-directory: Specs

    - name: list
      run: zip -sf portal-input.zip
      working-directory: Specs

    - name: inplace-import
      run: curl -X PUT --url 'https://api.apimatic.io/api-entities/${{ secrets.API_ENTITY_ID }}' -H 'content-type:multipart/form-data' -H 'Authorization:X-Auth-Key ${{ secrets.API_KEY }}' -H "Accept:application/json" -F 'file=@Specs/portal-input.zip'

# Uncomment the following step to publish your Portal. The portal must first be published manually for this step to work successfully.
#     - name: publish-portal
#       run: curl --location --request PUT 'https://www.apimatic.io/api/api-entities/${{ secrets.API_ENTITY_ID }}/portal/publish' -H 'Content-Length:0' -H 'Authorization:X-Auth-Key ${{ secrets.API_KEY }}'
      
 
